# Generated by Django 5.1 on 2024-09-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0002_user_bus_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
