# Generated by Django 5.1 on 2025-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0004_patient_day_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='efternavn', max_length=255),
            preserve_default=False,
        ),
    ]
