# Generated by Django 5.1 on 2025-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0005_patient_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_frontdesk',
            field=models.BooleanField(default=False),
        ),
    ]
