# Generated by Django 5.1 on 2025-09-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0006_siteuser_is_frontdesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('bus_time_manual', models.TimeField(blank=True, null=True)),
                ('bus_time_computed', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('translator', models.BooleanField(default=False)),
                ('has_taxi', models.BooleanField(default=False)),
                ('wheelchair', models.BooleanField(default=False)),
                ('trolley', models.BooleanField(default=False)),
                ('companion', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('departure_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bus_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='departure_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='has_taxi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='trolley',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wheelchair',
        ),
        migrations.AddField(
            model_name='patient',
            name='default_accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_patients', to='dgp_bus.accommodation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='day_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name', 'last_name'], name='dgp_bus_pat_name_14d250_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dgp_bus.accommodation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dgp_bus.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dgp_bus.patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='dgp_bus_app_appoint_54c573_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='dgp_bus_app_appoint_f839c6_idx'),
        ),
    ]
