# Generated by Django 5.1 on 2024-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0006_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='translator',
            field=models.BooleanField(),
        ),
    ]
