# Generated by Django 5.1 on 2024-09-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0007_alter_user_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='translator',
            field=models.BooleanField(default=False),
        ),
    ]
