# Generated by Django 5.1 on 2024-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0009_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff')], default='patient', max_length=10),
        ),
    ]
