# Generated by Django 5.1 on 2024-09-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
