# Generated by Django 5.1 on 2024-09-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0013_remove_user_is_admin_remove_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=100)),
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('bus_time', models.TimeField(blank=True, null=True)),
                ('translator', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgp_bus.hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='users',
            field=models.ManyToManyField(related_name='rides', to='dgp_bus.patient'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
