# Generated by Django 5.1 on 2024-09-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0015_remove_staffadminuser_email_staffadminuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffadminuser',
            old_name='username',
            new_name='email',
        ),
    ]
