# Generated by Django 5.1 on 2024-09-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0016_rename_username_staffadminuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
