# Generated by Django 5.1 on 2024-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0017_patient_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_taxi',
            field=models.BooleanField(default=False),
        ),
    ]
