# Generated by Django 5.1 on 2024-10-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0020_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dgp_bus.accommodation'),
        ),
    ]
