# Generated by Django 5.1 on 2024-11-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0021_accommodation_patient_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='users',
        ),
        migrations.AddField(
            model_name='ride',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='RidePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgp_bus.patient')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgp_bus.ride')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='patients',
            field=models.ManyToManyField(related_name='rides', through='dgp_bus.RidePatient', to='dgp_bus.patient'),
        ),
    ]
