# Generated by Django 5.1 on 2024-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0022_remove_ride_arrival_time_remove_ride_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fake_hospital',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
