# Generated by Django 5.1 on 2024-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp_bus', '0026_alter_siteuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='companion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='trolley',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
    ]
